# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=200)),
                ('votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u59d3\u540d')),
                ('pub_date', models.DateTimeField(verbose_name='\u66f4\u65b0\u65e5\u671f')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officers.Officer'),
        ),
    ]
