# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=200)),
                ('votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('pub_date', models.DateTimeField(verbose_name='更新日期')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=2, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('partytime', models.DateField(verbose_name='入党时间')),
                ('jobtime', models.DateField(verbose_name='工作时间')),
                ('native', models.CharField(default='湖南永州', max_length=20, verbose_name='籍贯')),
                ('nation', models.CharField(default='汉', max_length=20, verbose_name='民族')),
                ('dutylevel', models.CharField(default='无', max_length=20, verbose_name='职务层次')),
                ('id_number', models.CharField(default='无', max_length=18, verbose_name='身份证号')),
                ('jobtitle', models.CharField(max_length=50, verbose_name='工作单位及职务')),
                ('fulltimeedu', models.CharField(max_length=10, verbose_name='全日制学历')),
                ('fulltimedeg', models.CharField(max_length=10, verbose_name='全日制学位')),
                ('parttimeedu', models.CharField(max_length=10, null=True, verbose_name='在职学历')),
                ('parttimedeg', models.CharField(max_length=10, null=True, verbose_name='在职学位')),
                ('managefield', models.CharField(max_length=50, verbose_name='分管工作')),
                ('profile', models.TextField(max_length=1000, null=True, verbose_name='简历')),
            ],
            options={
                'verbose_name_plural': '干部',
                'verbose_name': '干部',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officers.Officer'),
        ),
    ]
