# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officer',
            old_name='dutylevel',
            new_name='duty_level',
        ),
    ]
