# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0002_auto_20170220_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officer',
            old_name='fulltimedeg',
            new_name='full_time_deg',
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='fulltimeedu',
            new_name='full_time_edu',
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='jobtime',
            new_name='job_time',
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='jobtitle',
            new_name='job_title',
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='managefield',
            new_name='manage_field',
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='parttimeedu',
            new_name='part_time_edu',
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='parttimedeg',
            new_name='partt_ime_deg',
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='partytime',
            new_name='party_time',
        ),
    ]
