# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0002_auto_20170220_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='duty_level',
            field=models.CharField(default='\u65e0', max_length=20, verbose_name='\u804c\u52a1\u5c42\u6b21'),
        ),
        migrations.AddField(
            model_name='officer',
            name='id_number',
            field=models.CharField(default='\u65e0', max_length=18, verbose_name='\u8eab\u4efd\u8bc1\u53f7'),
        ),
        migrations.AddField(
            model_name='officer',
            name='nation',
            field=models.CharField(default='\u6c49', max_length=20, verbose_name='\u6c11\u65cf'),
        ),
        migrations.AddField(
            model_name='officer',
            name='native',
            field=models.CharField(default='\u6e56\u5357\u6c38\u5dde', max_length=20, verbose_name='\u7c4d\u8d2f'),
        ),
    ]
