# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0003_auto_20170220_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officer',
            old_name='partt_ime_deg',
            new_name='part_time_deg',
        ),
    ]
