# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0003_auto_20170220_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='birthday',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u51fa\u751f\u65e5\u671f'),
            preserve_default=False,
        ),
    ]
