# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0004_officer_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='birthday',
            field=models.DateField(verbose_name='\u51fa\u751f\u65e5\u671f'),
        ),
    ]
