# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='pub_datte',
            new_name='pub_date',
        ),
    ]
