# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170218_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='question',
            new_name='name',
        ),
    ]
